echo "********* Installing commitizen *********"
pip install --user -U Commitizen

echo "********* Aliasing pnpm as npm *********"
alias --save npm="pnpm"

echo "********* Installing fish plugins *********"
fisher install jorgebucaran/fisher \
    edc/bass \
    jorgebucaran/hydro \
    jethrokuan/z \
    jorgebucaran/nvm.fish \
    franciscolourenco/done \
    jorgebucaran/replay.fish \
    jorgebucaran/spark.fish \
    meaningful-ooo/sponge \
    jorgebucaran/autopair.fish \
    jorgebucaran/getopts.fish \
    nickeb96/puffer-fish \
    gazorby/fish-abbreviation-tips \
    ilancosman/tide@v5 \
    fabioantunes/base16-fish-shell \
    acomagu/fish-async-prompt

echo "********* Updating permissions on /workspace *********"
chmod 777 /workspace

echo "********* Generating a new SSH GitHub key *********"
mkdir -p -- ~/.ssh
yes | ssh-keygen -q -t rsa -b 2048 -N '' -C "vm-autogenerated" -f ~/.ssh/id_rsa
echo "Paste the following into your GitHub SSH key at https://github.com/settings/ssh/new :"
cat ~/.ssh/id_rsa.pub
