set_color green
echo "********* Installing commitizen *********"
set_color normal
pip install --user -U Commitizen

set_color green
echo "********* Aliasing pnpm as npm *********"
set_color normal
alias --save npm="pnpm"

set_color green
echo "********* Installing fish plugins *********"
set_color normal
fisher install jorgebucaran/fisher \
    edc/bass \
    jorgebucaran/hydro \
    jethrokuan/z \
    jorgebucaran/nvm.fish \
    franciscolourenco/done \
    jorgebucaran/replay.fish \
    jorgebucaran/spark.fish \
    meaningful-ooo/sponge \
    jorgebucaran/autopair.fish \
    jorgebucaran/getopts.fish \
    nickeb96/puffer-fish \
    gazorby/fish-abbreviation-tips \
    ilancosman/tide@v5 \
    fabioantunes/base16-fish-shell \
    acomagu/fish-async-prompt

set_color green
echo "********* Updating permissions on /workspace *********"
set_color normal
chmod 777 /workspace

set_color green
echo "********* Generating a new SSH GitHub key *********"
set_color normal
mkdir -p -- ~/.ssh
yes | ssh-keygen -q -t rsa -b 2048 -N '' -C "vm-autogenerated" -f ~/.ssh/id_rsa
set_color red
echo "Paste the following into your GitHub SSH key at https://github.com/settings/ssh/new:"
set_color yellow
cat ~/.ssh/id_rsa.pub
set_color normal
