function print
    set -l args $argv
    if test -n "$args[2]"
        set_color $args[1]
        set -e args[1]
    end
    echo "********* $args *********"
    set_color normal
end

print green "Aliasing pnpm as npm"
alias --save npm="pnpm"

print green "Installing fish plugins"
fisher install jorgebucaran/fisher \
edc/bass \
jorgebucaran/hydro \
jorgebucaran/nvm.fish \
franciscolourenco/done \
jorgebucaran/replay.fish \
meaningful-ooo/sponge \
jorgebucaran/autopair.fish \
jorgebucaran/getopts.fish \
nickeb96/puffer-fish
rm /home/node/.config/fish/functions/fish_mode_prompt.fish
rm /home/node/.config/fish/functions/fish_prompt.fish
fisher install ilancosman/tide@v5

print green "Updating permissions on /workspace"
chown node /workspace

if test -n -d /workspace/.ssh
    print green "Generating a new SSH GitHub key"
    mkdir -p -- /workspace/.ssh
    yes | ssh-keygen -q -t ed25519 -N '' -C "vm-autogenerated" -f /workspace/.ssh/id_ed25519
    print red "Paste the following into your GitHub SSH key at https://github.com/settings/ssh/new:"
    set_color yellow
    cat /workspace/.ssh/id_ed25519.pub
    set_color normal
    echo "Host github.com" >> ~/.ssh/config
    echo "  IdentityFile /workspace/.ssh/id_ed25519.pub" >> ~/.ssh/config
end
